# Generated by Django 4.2.6 on 2023-10-31 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carer', '0002_childminderkyc_identity_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childminderkyc',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
