# Generated by Django 4.2.6 on 2023-11-19 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_kids', models.IntegerField()),
                ('age_group', models.CharField(choices=[('select', 'Select'), ('newborn', 'Newborn'), ('toddler', 'Toddler'), ('pre-school', 'Pre-school'), ('primary_school', 'Primary school'), ('teenager(12+years)', 'Teenager(12+years)')], default='select', max_length=50)),
                ('additional_care', models.CharField(blank=True, choices=[('select', 'Select'), ('cooking', 'Cooking'), ('putting_kids_to_bed', 'Putting kids to bed'), ('homework_help', 'Homework help')], default='select', max_length=50, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('slot_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CareSlots',
                'ordering': ['-date_created'],
            },
        ),
    ]
