# Generated by Django 4.2.6 on 2023-11-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_slot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careslot',
            name='additional_care',
            field=models.CharField(blank=True, choices=[('select', 'Select'), ('cooking', 'Cooking'), ('putting kids to bed', 'Putting kids to bed'), ('homework help', 'Homework help')], default='select', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='careslot',
            name='age_group',
            field=models.CharField(choices=[('select', 'Select'), ('newborn', 'Newborn'), ('Toddler', 'toddler'), ('pre-school', 'Pre-school'), ('primary school', 'Primary school'), ('teenager(12+years)', 'Teenager(12+years)')], default='select', max_length=50),
        ),
    ]
